baseURL = ""
languageCode = "en-us"
title = "Rock of Ages"
paginate = 12

# Section page menu
[params]
  subtitle          = "Rock of Ages Eletrical Company"
  cover             = "images/cover-img.jpg"
  description       = "General electrical merchants, giant in rural electrification both surface and under ground wiring such as: Transformers, Feeder Pillar Unit, Cables and Insulators"
  metaDespecription = "Electrical Equipments"
  customCSS         = [""]
  RSSLink           = ""
  tags              = ["shopping", "catalogue", "product catalogue", "ecommerce", "minimal", "responsive"]

  logo              = "images/logo-1.png"
  favicon           = "images/favicon.ico"

# socail media profile usernames
  twitterName       = "otisidev"
  fbName            = "otisidev"

  devsName          = "Looptrace"
  devsWebsite       = "https://www.looptrace.com"

  #Contact information
  contactName             = ""
  contactMainAddress      = ""
  contactNumber          = 2348037270490
  contactShopLocations    = [""]

[permalinks]
  products  = "/product/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 150

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 90
