backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "static/images"
public_folder: "images"

collections:
  - name:       "products"
    label:      "Product"
    create:     true
    slug:       "{{slug}}"
    folder:     "Content/products"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime" , required: true}
      - {label: "Thumbnail Image", name: "thumbnailImage", widget: "image", required: true}
      - {label: "Actual Price", name: "actualPrice", widget: "number", required: true}
      - {label: "Compare Price", name: "comparePrice", widget: "number", required: true}
      - {label: "Unit of Measure", name: "uniteMeasure", widget: "string", required: true}
      - {label: "In Stock", name: "inStock", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", required: true}
      - {label: "Categories", name: "categories", widget: "list", required: true}
      - {label: "Summary", name: "summary", widget: "text", required: true}
      - {label: "draft", name: "draft", widget: "hidden", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
